### PR TITLE
Update Win Confidence

### PR DESCRIPTION
**Pull request by martdamp**
Fix Math in getWinConfidence()
It's now according to the article linked

### CODE REVIEW

**Comment by NathanWolf** [comment]
@killme this one's up to you since you wrote that code. Do you all even use this plugin, though?

**Comment by NathanWolf** [comment]
Oops, ha just noticed the author of this PR :)

Well I assume it's fine then?

**Comment by killme** [comment]
I missed some things in the formula. This should fix it.

**Comment by NathanWolf** [comment]
Thanks, guys!

**Pull request merged**
